var express = require('express');
const Tank = require('../models/Tank');
var router = express.Router();
/**
 * A tank with different specifications
 * @typedef {object} Tank
 * @property {string} name.required - A unique name
 * @property {number} maxHealth - The starting health of the tank
 * @property {number} damage - The damage generated by a single hit
 * @property {number} range - The shot range of tank
 * @property {number} speed - The the number of squares the tank
 */

/**
 * GET /tanks
 * @summary Returns a list of all the tanks currently in the database
 * @tags tank
 * @return {array<Tank>} 200 - success response - application/json
 */
router.get('/', async(_req, res) => {
    const tanks = await Tank.find();
    res.send(tanks);
});

/**
 * POST /tanks
 * @summary Creates a tank and stores it into the database
 * @tags tank
 * @param {Tank} request.body.required - The tank object to be created
 * @return {Tank} 201 - tank response
 */
router.post('/', async(req, res) => {
    Tank.create({
        name: req.body.name,
        maxHealth: req.body.maxHealth,
        damage: req.body.damage,
        range: req.body.range,
        speed: req.body.speed
    }).then((tank) => res.send(tank));
});

module.exports = router;